### ISSUE TITLE
does not copy over subtitles to the new mp4

### ISSUE THREAD

**Issue by FuugoClay** [jspw/Little-Fun-Stuffs#1]
### When I run (the latest ver. ffmpeg as of this post) the following: 

**__ffmpeg -i /INPUTFILE.mkv -codec copy OUTPUTFILE.mp4_**_

### The subtitle stream is not copied over.  

-------------------------------------------------
### INPUTFILE.mkv details:
Input #0, matroska,webm, from 'INPUTFILE.mkv':
  Metadata:
    creation_time   : 2022-06-19T09:43:26.000000Z
    encoder         : libebml v1.4.2 + libmatroska v1.6.4
    TITLE           : Encoded By: mkvAnime
    Website         : Google Search - mkvAnime.com
  Duration: 02:21:53.31, start: 0.000000, bitrate: 4073 kb/s
  Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x804 [SAR 1:1 DAR 160:67], 24 fps, 24 tbr, 1k tbn (default) (forced)
    Metadata:
      title           : mkvAnime
      BPS             : 3432045
      DURATION        : 02:21:53.167000000
      NUMBER_OF_FRAMES: 204316
      NUMBER_OF_BYTES : 3652196555
      _STATISTICS_WRITING_APP: mkvmerge v62.0.0 ('Apollo') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2022-06-19 09:43:26
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(hin): Audio: ac3, 48000 Hz, 5.1(side), fltp, 640 kb/s (default) (forced)
    Metadata:
      title           : mkvAnime
      BPS             : 640000
      DURATION        : 02:21:53.312000000
      NUMBER_OF_FRAMES: 266041
      NUMBER_OF_BYTES : 681064960
      _STATISTICS_WRITING_APP: mkvmerge v62.0.0 ('Apollo') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2022-06-19 09:43:26
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(eng): Subtitle: subrip (default) (forced)
    Metadata:
      title           : mkvAnime
      BPS             : 56
      DURATION        : 02:11:49.833000000
      NUMBER_OF_FRAMES: 1950
      NUMBER_OF_BYTES : 55494
      _STATISTICS_WRITING_APP: mkvmerge v62.0.0 ('Apollo') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2022-06-19 09:43:26
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTE

--------------------------------------------------

### OUTPUTFILE.mp4 details:
_ffprobe -i OUTPUTFILE.mp4_
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from OUTPUTFILE.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomdby1iso2avc1mp41
    title           : Encoded By: mkvAnime
    encoder         : Lavf59.27.100
  Duration: 02:21:53.31, start: 0.000000, bitrate: 4079 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x804 [SAR 1:1 DAR 160:67], 3432 kb/s, 24 fps, 24 tbr, 16k tbn (default) (forced)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](hin): Audio: ac3 (ac-3 / 0x332D6361), 48000 Hz, 5.1(side), fltp, 640 kb/s (default) (forced)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
    Side data:
      audio service type: main

**Comment by jspw** [comment]
Can you try this one ? @FuugoClay 

`ffmpeg -i input.mkv -vf subtitles=input.mkv -acodec copy output.mp4`

This will actually integrate the subtitle with  the mp4 video and it will take time !
