### ISSUE TITLE
Add a prompt asking if user wants his original files to be deleted

### ISSUE THREAD

**Issue by pavtiger** [jspw/Little-Fun-Stuffs#3]
I think a script that converts mkv to mp4 should not delete original files. User can do that by himself if he decides that the he is glad with the converted result and doesn't require original files, what if the result turns out to be corrupted somewhere in the converting process. Then all my data is lost! Furthermore, for some like me, I like to keep all sources just in case. 

That being said, I do see this feature being useful for some people, so I think the best choice would be to introduce a prompt asking user if he wants his original files to be deleted and the default choice should be **"No"**.

_**You can't just delete user's files without asking him.**_

**Comment by jspw** [comment]
Hey Paul,
Thanks for your concern. Actually It was made for my personal use at first.
As you have mentioned I will add that Prompt option whenever I get free
time.
Btw If you are interested you can add those features and give a pr. I will
be happy to review and merge.
